http:
  port: 8080

admin:
  port: 9876
  host: 0.0.0.0

apiEndpoints:
  decks:
    host: '*'
    paths: '/decks*'
    methods: ['GET', 'POST', 'PUT', 'DELETE']
  
  cards:
    host: '*'
    paths: 
      - '/card*'
      - '/cards*'
    methods: ['GET', 'POST', 'PUT', 'DELETE']

serviceEndpoints:
  decksService:
    url: 'http://decks-service:4052'
  cardsService:
    url: 'http://card-service:3000'

policies:
  - proxy

pipelines:
  default:
    apiEndpoints:
      - decks
      - cards
    policies:
      - proxy:
          condition:
            name: pathMatch
            pattern: '/decks*'
          action:
            serviceEndpoint: decksService
            changeOrigin: true
      - proxy:
          condition:
            name: pathMatch
            pattern: '/card*'
          action:
            serviceEndpoint: cardsService
            changeOrigin: true
      - proxy:
          condition:
            name: pathMatch
            pattern: '/cards*'
          action:
            serviceEndpoint: cardsService
            changeOrigin: true